### ISSUE TITLE
Numbers misleading

### ISSUE THREAD

**Issue by lbenedix** [KnollFrank/HowBadIsMyBatch#2]
Hi, 

for a given Batch it looks like 50% of the vaccine shots are deadly. You are missing the size of the batch to make this claim.

You only show that 50% of the averse event reports are deaths, it says nothing about the Lethality of the batch.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/266532/205049265-35207ebb-01ea-4e10-8304-73df14598684.png">

**Comment by KnollFrank** [comment]
Thank you for pointing this out, but please read https://www.howbadismybatch.com/lethal.html
