### ISSUE TITLE
Data incomplete/Wrong

### ISSUE THREAD

**Issue by Yiannis128** [KnollFrank/HowBadIsMyBatch#4]
I think this batch may be read wrong since it looks weird on the table. Also it's an AstraZeneca batch.

![image](https://user-images.githubusercontent.com/9535618/211850727-74412195-ecab-4906-9e55-b008c1ca18b7.png)

**Comment by KnollFrank** [comment]
The VAERS database from which this project pulls it's data has some entries for batch PW40010 listing both PFIZER-BIONTECH and also UNKNOWN MANUFACTURER as manufacturers which are both erroneous entries as you pointed out. You can check this by following this [link](https://medalerts.org/vaersdb/findfield.php?TABLE=ON&GROUP1=AGE&EVENTS=ON&VAXLOT=PW40010).
