### ISSUE TITLE
UK

### ISSUE THREAD

**Issue by moominka** [KnollFrank/HowBadIsMyBatch#6]
Heya, just to mention: https://knollfrank.github.io/HowBadIsMyBatch/data/batchCodeTables/United%20Kingdom.json

**Comment by KnollFrank** [comment]
Excuse me, I don't understand what is wrong with the link you mentioned?

**Comment by rusco** [comment]
I get a 404 , page not found. You probably did some refactoring of your data/project layout or removed the json file.

**Comment by KnollFrank** [comment]
@rusco Yes, this file was removed, because there are no country specific batch code tables any more.
